server.port=${PORT:8081}

# 1. Nonaktifkan Auto-Configuration Database Relasional
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, \
                             org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, \
                             org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

# 2. Bypass Spring Security UserDetailsService agar tidak mencari database SQL
spring.security.user.name=admin
spring.security.user.password=admin

# 3. Kunci Siklus Hidup Web Server Tomcat di Cloud Environment
spring.main.web-application-type=servlet